openapi: 3.0.1
info:
  version: 1.0.0
  title: Transports specification
  license:
    name: MIT
paths:
  /places:
    get:
      summary: List all the places
      operationId:
      tags:
        - places
      responses:
        '200':
          description: A paged array of places
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Places"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a place
      tags:
        - places
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /places/{placeId}:
    get:
      summary: Info for a specific place
      tags:
        - places
      parameters:
        - name: placeId
          in: path
          required: true
          description: The id of the place to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Place"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Place:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        postedDate:
          type: string
          format: date
    Places:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Place"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
